### ISSUE TITLE
How to regenerate Refresh Token if it has expired?

### ISSUE THREAD

**Issue by abhisheksoni27** [paulmolluzzo/test-deploy-chrome#1]
It is noted here: https://developer.chrome.com/webstore/using_webstore_api#beforeyoubegin that the tokens expire after 40 minutes. What happens after that?

**Comment by paulmolluzzo** [comment]
The `REFRESH_TOKEN` itself doesn’t expire, it’s used to get a new `CLIENT_SECRET` because it’s that secret that expires. It’s not done by this library, but instead a dependency (of a dependency) does that work here: https://github.com/DrewML/chrome-webstore-upload/blob/master/index.js#L57

Hopefully this gives you some insight into how this works!
